export const CHALLENGES = [
  { label: 'The Edge', code: 'EDG' },
  { label: 'Cresting Success', code: 'CrSu' },
  { label: 'Bonus Buckets', code: 'BB' },
  { label: 'Sharp Shooter', code: 'SS' },
  { label: 'Rail Rider', code: 'RR' },
  { label: 'Three Ring Putt', code: 'TRP' },
  { label: 'Lucky Bounce', code: 'LB' },
  { label: 'Perfect Timing', code: 'PT' },
  { label: 'Turbine', code: 'Tur' },
  { label: 'Canyon Run', code: 'CyRu' },
  { label: 'Inversion', code: 'Inv' },
  { label: 'The Launcher', code: 'Lau' },
  { label: 'The Hex', code: 'Hex' },
  { label: 'Pop Quiz', code: 'PQ' },
  { label: 'Lucky Duck', code: 'LD' },
  { label: 'Yes / No', code: 'Y/N' },
  { label: 'Chutes & Spinners', code: 'Ch&Sp' },
  { label: "Putt O' Gold", code: 'POG' },
  { label: 'Mount Molehill', code: 'MM' },
  { label: 'Lucky Shuffle', code: 'LS' },
  { label: 'Summit Scramble', code: 'SuSc' },
  { label: 'Tilt', code: 'Tlt' },
]

export const CHALLENGE_MAP = Object.fromEntries(CHALLENGES.map((c) => [c.code, c]))
